deployTarget: LOCAL
pachd:
    metrics:
        enabled: false
    clusterDeploymentID: dev
    activateEnterprise: true
    enterpriseSecret: "50PO0HynZjt7oWqWbKnQlLN6j2dl97rq"
    rootToken: "V4Ptmxchcj04TY5vmngJAD0RiuJ3JYc6"
    oauthClientSecret: "p2BDmthvG91dKS22n1YnbvmZW0ZRYW91"
    storage:
        backend: MINIO
        minio:
            bucket: "pachyderm-test"
            endpoint: "minio.default.svc.cluster.local:9000"
            id: "minioadmin"
            secret: "minioadmin"
            secure: "false"
            signature: ""
    localhostIssuer: "true"
postgresql:
    postgresqlPassword: "abc123321cba"
    postgresqlPostgresPassword: "npLvsvhGcF"
console:
    enabled: true
    config:
        oauthClientSecret: "Hz1iySrX5Gm8owpRrYMM8vY7NXfgxhUs"
ingress:
    enabled: false
proxy:
    enabled: true
    service:
        type: NodePort
        legacyPorts:
            console: 30400
            grpc: 30650
            s3Gateway: 30600
            oidc: 30657
            identity: 30658
            metrics: 30656
